import type {
  AdjustmentRequest,
  ClassProfile,
  ConstraintRule,
  MetricCard,
  NotificationChannel,
  OptimizationSuggestion,
  RoomResource,
  ScheduleSlot,
  TeacherAvailability,
  HeatmapSnapshot,
} from './types';

export const CLASS_PROFILES: ClassProfile[] = [
  {
    id: 'cls-ielts-elite',
    name: 'IELTS 冲刺精英班',
    program: '语言培训 · 雅思',
    level: '冲刺 6 周',
    capacity: 18,
    enrolled: 16,
    advisor: '班主任 Vivian',
    leadTeacher: '外教 Daniel',
    assistants: ['助教 Kelly'],
    mode: 'hybrid',
    scheduleStatus: 'in-progress',
    startDate: '2024-12-02',
    endDate: '2025-01-12',
  },
  {
    id: 'cls-ap-calc',
    name: 'AP Calculus AB A 班',
    program: '国际课程 · AP',
    level: '常规 12 周',
    capacity: 25,
    enrolled: 22,
    advisor: '班主任 Leo',
    leadTeacher: '张博（数学）',
    assistants: ['助教 Hannah'],
    mode: 'online',
    scheduleStatus: 'published',
    startDate: '2024-11-18',
    endDate: '2025-02-09',
  },
  {
    id: 'cls-research-lab',
    name: '科研孵化实验班 · 物理方向',
    program: '科研培训',
    level: '项目制 8 周',
    capacity: 12,
    enrolled: 11,
    advisor: '班主任 Olivia',
    leadTeacher: '教授顾问 Mark',
    assistants: ['助教 Emily', '助教 Max'],
    mode: 'offline',
    scheduleStatus: 'draft',
    startDate: '2025-01-06',
    endDate: '2025-03-02',
  },
];

export const SCHEDULE_SLOTS: ScheduleSlot[] = [
  {
    id: 'slot-001',
    classId: 'cls-ielts-elite',
    topic: '写作 Task 2 结构设计',
    teacher: '外教 Daniel',
    room: '线上 · Zoom 981-213',
    startTime: '2024-12-09 19:30',
    endTime: '2024-12-09 21:30',
    mode: 'hybrid',
    status: 'scheduled',
    notes: '同步录制上传知识库',
  },
  {
    id: 'slot-002',
    classId: 'cls-ielts-elite',
    topic: '口语 Part 2 实战演练',
    teacher: '外教 Daniel',
    room: '上海徐家汇 · 3F-06',
    startTime: '2024-12-14 14:00',
    endTime: '2024-12-14 16:00',
    mode: 'hybrid',
    status: 'adjusted',
    notes: '教室调换至 3F-06，AI 语音评估同步开启',
  },
  {
    id: 'slot-003',
    classId: 'cls-ap-calc',
    topic: '导数应用 · 速度与加速度',
    teacher: '张博',
    room: '线上 · ClassIn 302-883',
    startTime: '2024-12-10 18:30',
    endTime: '2024-12-10 20:30',
    mode: 'online',
    status: 'scheduled',
  },
  {
    id: 'slot-004',
    classId: 'cls-research-lab',
    topic: '科研方法论 · 选题工作坊',
    teacher: '教授顾问 Mark',
    room: '上海虹口 · 实验室 2F',
    startTime: '2025-01-08 13:30',
    endTime: '2025-01-08 16:30',
    mode: 'offline',
    status: 'pending',
    notes: '待确认实验设备校准',
  },
];

export const CONSTRAINT_RULES: ConstraintRule[] = [
  {
    id: 'constraint-001',
    title: '教师日工作时长超限',
    description: '张博 当日排课 4 小时，已与教研会议冲突，需要调整周二晚课程。',
    severity: 'error',
    impactedClasses: ['AP Calculus AB A 班'],
    resolution: '建议改到周三同一时间段，由助教 Hannah 协同。',
  },
  {
    id: 'constraint-002',
    title: '教室容量不足提示',
    description: '徐家汇 3F-06 教室容纳 16 人，当前报名 18 人，需拆班或启用混合模式。',
    severity: 'warning',
    impactedClasses: ['IELTS 冲刺精英班'],
  },
];

export const OPTIMIZATION_SUGGESTIONS: OptimizationSuggestion[] = [
  {
    id: 'optim-001',
    category: 'teacher-load',
    description: '将 IELTS 班写作课替换为双师模式，平均教师工作时长下降 12%。',
    impact: 'high',
    actionOwner: '教务运营',
  },
  {
    id: 'optim-002',
    category: 'room-utilization',
    description: '建议将实验班上午时段调整至周日，提升实验室利用率 18%。',
    impact: 'medium',
    actionOwner: '实验中心',
  },
  {
    id: 'optim-003',
    category: 'continuity',
    description: 'AP 课程周末可增加作业答疑，增强学习连续性并减少补课申请。',
    impact: 'low',
    actionOwner: '教研组',
  },
];

export const TEACHER_AVAILABILITIES: TeacherAvailability[] = [
  {
    id: 'teacher-daniel',
    name: 'Daniel Carter',
    subjects: ['IELTS Speaking', 'IELTS Writing'],
    weeklyHours: 24,
    bookedHours: 18,
    preferredSlots: ['周二 19:00', '周四 19:00', '周六 14:00'],
    status: 'available',
  },
  {
    id: 'teacher-zhangbo',
    name: '张博',
    subjects: ['AP Calculus', 'SAT Math'],
    weeklyHours: 28,
    bookedHours: 26,
    preferredSlots: ['周二 18:30', '周五 18:30'],
    status: 'overload',
  },
  {
    id: 'teacher-mark',
    name: 'Mark Howard',
    subjects: ['Physics Research', 'Lab Skills'],
    weeklyHours: 20,
    bookedHours: 12,
    preferredSlots: ['周三 13:30', '周五 10:00'],
    status: 'available',
  },
];

export const ROOM_RESOURCES: RoomResource[] = [
  {
    id: 'room-3f-06',
    name: '徐家汇 3F-06',
    type: 'classroom',
    capacity: 16,
    equipment: ['4K 投屏', '录音系统', 'AI 语音评估'],
    availableHours: ['周一-周五 09:00-21:00', '周六 09:00-18:00'],
    utilization: 0.78,
  },
  {
    id: 'room-lab-2f',
    name: '虹口实验室 2F',
    type: 'lab',
    capacity: 20,
    equipment: ['实验台', '示波器', '3D 打印机'],
    availableHours: ['周二-周日 10:00-22:00'],
    utilization: 0.64,
  },
  {
    id: 'room-zoom-981',
    name: 'Zoom 981-213',
    type: 'virtual',
    capacity: 100,
    equipment: ['录制', 'Breakout Rooms', 'AI 自动转写'],
    availableHours: ['全时段'],
    utilization: 0.52,
  },
];

export const ADJUSTMENT_REQUESTS: AdjustmentRequest[] = [
  {
    id: 'adjust-001',
    className: 'IELTS 冲刺精英班',
    requester: '学员 Iris',
    type: 'leave',
    reason: '12 月 14 日有托福考试，希望改至 12 月 15 日晚。',
    targetDate: '2024-12-15',
    status: 'pending',
    reviewer: 'Vivian',
  },
  {
    id: 'adjust-002',
    className: 'AP Calculus AB A 班',
    requester: '老师 张博',
    type: 'reschedule',
    reason: '周二晚需参加教研会，希望调至周三同一时间。',
    targetDate: '2024-12-11',
    status: 'approved',
    reviewer: 'Leo',
  },
  {
    id: 'adjust-003',
    className: '科研孵化实验班 · 物理方向',
    requester: '助教 Emily',
    type: 'makeup',
    reason: '实验室设备维护，需安排补课。',
    targetDate: '2025-01-12',
    status: 'pending',
    reviewer: 'Olivia',
  },
];

export const NOTIFICATION_CHANNELS: NotificationChannel[] = [
  {
    id: 'notify-email',
    name: '邮件通知',
    channel: 'email',
    description: '自动推送课程提醒、调课确认、补课安排。',
    autoSync: true,
    lastSync: '2024-12-08 10:12',
  },
  {
    id: 'notify-sms',
    name: '短信提醒',
    channel: 'sms',
    description: '临时变更、紧急停课的信息直达。',
    autoSync: false,
    lastSync: '2024-12-07 21:45',
  },
  {
    id: 'notify-calendar',
    name: 'Google Calendar',
    channel: 'calendar',
    description: '同步老师与学员个人日历，支持事件更新。',
    autoSync: true,
    lastSync: '2024-12-08 07:30',
  },
  {
    id: 'notify-dingtalk',
    name: '钉钉群机器人',
    channel: 'dingtalk',
    description: '面向老师与班主任的即时通知群，推送调课审批结果。',
    autoSync: true,
    lastSync: '2024-12-08 09:05',
  },
];

export const KPI_METRICS: MetricCard[] = [
  { id: 'kpi-conflict', title: '排课冲突率', value: '3.2%', delta: '-1.1%', trend: 'down' },
  { id: 'kpi-utilization', title: '教室利用率', value: '74%', delta: '+6%', trend: 'up' },
  { id: 'kpi-teacher', title: '教师准时率', value: '96%', delta: '+2%', trend: 'up' },
  { id: 'kpi-makeup', title: '补课完成率', value: '88%', delta: '-4%', trend: 'down' },
];

export const HEATMAP_SNAPSHOT: HeatmapSnapshot[] = [
  { id: 'mon-morning', label: '周一 上午', value: 68 },
  { id: 'mon-evening', label: '周一 晚间', value: 92 },
  { id: 'tue-evening', label: '周二 晚间', value: 98 },
  { id: 'wed-afternoon', label: '周三 下午', value: 74 },
  { id: 'sat-morning', label: '周六 上午', value: 85 },
  { id: 'sun-afternoon', label: '周日下午', value: 45 },
];
