import type { Partner } from './types';

export const mockPartners: Partner[] = [
  {
    id: 'partner-oxford',
    name: '牛津大学 · 计算机科学系',
    type: 'university',
    status: 'active',
    level: 'strategic',
    country: '英国',
    city: '牛津',
    website: 'https://www.cs.ox.ac.uk',
    summary: '聚焦人工智能与安全方向，支持联合培养与暑期科研营。',
    rating: 5,
    tags: ['联合培养', '博士推荐', 'AI'],
    ownerId: 'owner-zhaoli',
    ownerName: '赵丽',
    ownerTitle: '全球合作负责人',
    isFavorite: true,
    contacts: [
      {
        id: 'contact-oxford-1',
        name: 'Dr. Alice Carter',
        role: '国际合作主任',
        email: 'alice.carter@cs.ox.ac.uk',
        phone: '+44 20 1234 5678',
        linkedin: 'https://linkedin.com/in/alice-carter',
        isPrimary: true,
      },
      {
        id: 'contact-oxford-2',
        name: 'Michael Lee',
        role: '招生联络官',
        email: 'mlee@cs.ox.ac.uk',
        phone: '+44 20 8765 4321',
      },
    ],
    engagements: [
      {
        id: 'engagement-oxford-1',
        title: 'AI 联合培养计划',
        category: '联合招生',
        status: 'executing',
        contractStatus: 'signed',
        startDate: '2025-01-10',
        endDate: '2026-01-09',
        nextAction: '12 月 5 日提交成果总结',
        ownerName: '赵丽',
      },
    ],
    timelines: [
      {
        id: 'timeline-oxford-1',
        noteType: 'meeting',
        content: '年度绩效评估会议，确定 2025 学生名额 12 个。',
        nextAction: '12 月 1 日前发送候选名单',
        remindAt: '2025-11-28T09:00:00Z',
        createdAt: '2025-11-10T08:00:00Z',
        createdBy: 'owner-zhaoli',
        createdByName: '赵丽',
      },
      {
        id: 'timeline-oxford-2',
        noteType: 'document',
        content: '上传新版合作手册，包含联合实验室流程。',
        createdAt: '2025-10-22T10:00:00Z',
        createdBy: 'owner-zhaoli',
        createdByName: '赵丽',
      },
    ],
    risks: ['需关注英国签证政策变化'],
    internalNotes: '教授推荐流程需提前 6 周准备资料',
    highlight: '国际博士班 80% 入选率',
    lastUpdatedAt: '2025-11-12T10:00:00Z',
  },
  {
    id: 'partner-nus',
    name: '新加坡国立大学 · ECE 学院',
    type: 'university',
    status: 'negotiating',
    level: 'key',
    country: '新加坡',
    city: '新加坡',
    website: 'https://www.ece.nus.edu.sg',
    summary: '正在洽谈芯片设计与机器人方向实习合作。',
    rating: 4,
    tags: ['实习', '全球项目'],
    ownerId: 'owner-huxin',
    ownerName: '胡欣',
    ownerTitle: '东南亚区域负责人',
    isFavorite: false,
    contacts: [
      {
        id: 'contact-nus-1',
        name: 'Prof. Tan Wei',
        role: '学院副院长',
        email: 'tanwei@nus.edu.sg',
        phone: '+65 6123 7788',
        isPrimary: true,
      },
    ],
    engagements: [
      {
        id: 'engagement-nus-1',
        title: '机器人暑校',
        category: '短期项目',
        status: 'planning',
        contractStatus: 'reviewing',
        startDate: '2025-05-01',
        endDate: '2025-06-30',
        nextAction: '确认预算与奖学金名额',
        ownerName: '胡欣',
      },
    ],
    timelines: [
      {
        id: 'timeline-nus-1',
        noteType: 'call',
        content: '电话沟通合作条款，对方希望增加实验室参观环节。',
        nextAction: '整理方案并 11 月 20 日回访',
        remindAt: '2025-11-19T04:00:00Z',
        createdAt: '2025-11-08T03:00:00Z',
        createdBy: 'owner-huxin',
        createdByName: '胡欣',
      },
    ],
    lastUpdatedAt: '2025-11-08T05:00:00Z',
  },
  {
    id: 'partner-edtech',
    name: 'Flowith Labs · 教育科技合作社',
    type: 'company',
    status: 'active',
    level: 'key',
    country: '中国',
    city: '上海',
    summary: '为导师市场提供 AI 课程内容和企业导师资源。',
    rating: 4,
    tags: ['企业导师', 'AI 课程'],
    ownerId: 'owner-wangyi',
    ownerName: '王艺',
    ownerTitle: '行业合作经理',
    isFavorite: true,
    contacts: [
      {
        id: 'contact-edtech-1',
        name: '陈一凡',
        role: '商务负责人',
        email: 'partner@flowithlabs.com',
        phone: '+86 21 8888 6666',
        isPrimary: true,
      },
    ],
    engagements: [
      {
        id: 'engagement-edtech-1',
        title: 'AI 行业导师共建计划',
        category: '导师合作',
        status: 'executing',
        contractStatus: 'signed',
        startDate: '2025-09-01',
        endDate: '2026-02-28',
        nextAction: '12 月课程满意度回访',
        ownerName: '王艺',
      },
    ],
    timelines: [
      {
        id: 'timeline-edtech-1',
        noteType: 'email',
        content: '收到课程满意度 92% 报告，并附上提案。',
        createdAt: '2025-11-06T07:00:00Z',
        createdBy: 'owner-wangyi',
        createdByName: '王艺',
        attachments: [{ name: '满意度报告.pdf', url: '#' }],
      },
    ],
    risks: ['上一批导师 onboarding 耗时偏长'],
    highlight: '已输出 28 位行业导师',
    internalNotes: '适合实习课程打包销售',
    lastUpdatedAt: '2025-11-06T09:00:00Z',
  },
  {
    id: 'partner-mentor',
    name: '欧洲高校教授联合会',
    type: 'agency',
    status: 'prospecting',
    level: 'watch',
    country: '荷兰',
    city: '鹿特丹',
    summary: '提供 40+ 欧洲院校教授访学与短期授课机会。',
    tags: ['教授访学', '欧洲'],
    ownerId: 'owner-linyu',
    ownerName: '林宇',
    ownerTitle: '合作拓展',
    isFavorite: false,
    contacts: [
      {
        id: 'contact-mentor-1',
        name: 'Eva de Jong',
        role: '合作协调员',
        email: 'eva@eupa.org',
        phone: '+31 20 123 9999',
        isPrimary: true,
      },
    ],
    engagements: [],
    timelines: [
      {
        id: 'timeline-mentor-1',
        noteType: 'onsite',
        content: '教育展上初步交换需求，对方关注项目收益模式。',
        nextAction: '准备收益分成方案',
        createdAt: '2025-10-30T11:00:00Z',
        createdBy: 'owner-linyu',
        createdByName: '林宇',
      },
    ],
    lastUpdatedAt: '2025-10-30T12:00:00Z',
  },
];

export const fetchPartnerMockData = async (): Promise<Partner[]> => {
  await new Promise((resolve) => setTimeout(resolve, 400));
  return mockPartners;
};

