import { createElement } from 'react';
import {
  Activity,
  Clock4,
  Download,
  Mail,
  MapPin,
  MessageCircle,
  Phone,
  Sparkles,
  Star,
  Users,
} from 'lucide-react';

import type {
  AvailabilitySlot,
  InsightItem,
  MentorRecord,
  MentorTask,
  SharedResourceItem,
  SkillMatrixEntry,
  SummaryMetric,
} from './types';

export const MENTOR_TEAM: MentorRecord[] = [
  {
    id: 'mentor-1',
    name: '刘洋',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mentor-liuyang',
    primaryRole: '文书',
    secondaryRoles: ['质检'],
    email: 'liuyang@example.com',
    phone: '138-1111-2222',
    timezone: 'GMT+8',
    region: '北京',
    tags: ['CS', '美研', '文书专家'],
    languages: ['中文', '英文'],
    availabilityRate: 82,
    utilizationRate: 68,
    studentsCount: 14,
    satisfaction: 4.8,
    risk: '正常',
    lastActivity: '2025-11-08',
    headline: '文书专家 · 留学申请策略教练',
    bio: '前 500 强外企 HR 转型留学顾问，擅长挖掘学生差异化卖点，打造故事线型文书。已帮助 120+ 学生拿到 Top30 Offer。',
    focusAreas: ['美研 CS', '数据科学', '管理学'],
    serviceScope: ['个人陈述', '简历润色', '推荐信指引'],
    strengths: ['案例库丰富', '擅长深度访谈', '熟悉多学科申请逻辑'],
    education: [
      { school: '北京大学', degree: '新闻传播学 · 本科', period: '2010 - 2014' },
      { school: '哥伦比亚大学', degree: '教育管理 · 硕士', period: '2014 - 2016' },
    ],
    achievements: ['2024 年度学生满意度 4.9/5', '连续两年获「最佳文书导师」内部评选'],
    projects: [
      {
        title: '哥大应用分析 Offer 案例',
        year: '2024',
        result: '成功斩获 2 所 Top10 offer',
        description: '通过访谈挖掘学生在社团运营中的增长数据，设计数据叙事型 Essay。',
      },
      {
        title: '多背景转专业申请',
        year: '2023',
        result: '跨专业 GPA 3.2 成功进阶至 CMU 信息系统',
        description: '结合课程项目成果和行业调研，搭建「why us + why now」叙事。',
      },
    ],
    testimonials: [
      {
        author: '李同学 · 哥大 Analytics',
        role: '学生',
        comment: '刘老师把我零散的社团经历整理得很有逻辑，还帮我排练面试回答，非常靠谱。',
      },
      {
        author: '王同学 · NYU Tandon',
        role: '学生',
        comment: '从初稿到终稿每一版都给到很细的建议，最后拿到 4 个 offer。',
      },
    ],
    metrics: [
      { label: 'Offer 率', value: '92%', description: '近两年学生 offer 成功率' },
      { label: '平均交付周期', value: '14 天', description: '从访谈到定稿平均时长' },
    ],
    availabilityNotes: ['支持晚间 19:00 之后远程访谈', '擅长与职场申请者沟通背景提升'],
    tools: ['Notion', 'Grammarly', 'Miro'],
  },
  {
    id: 'mentor-2',
    name: '王璐',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mentor-wanglu',
    primaryRole: '材料',
    secondaryRoles: ['顾问'],
    email: 'wanglu@example.com',
    phone: '137-5555-6666',
    timezone: 'GMT+8',
    region: '上海',
    tags: ['材料质检', '财务材料'],
    languages: ['中文', '英文'],
    availabilityRate: 76,
    utilizationRate: 72,
    studentsCount: 10,
    satisfaction: 4.6,
    risk: '正常',
    lastActivity: '2025-11-07',
    headline: '材料审核专家 · ACCA 双证',
    bio: '五年四大审计经验，熟悉财务、商科项目申请，对材料规范与合规要求极为敏感。',
    focusAreas: ['财务/会计', '商科', '管理研培'],
    serviceScope: ['材料包整理', '清单梳理', '多语言翻译校对'],
    strengths: ['结构化思维', '多语材料审核', '跨项目协调'],
    education: [
      { school: '上海财经大学', degree: '会计学 · 本科', period: '2010 - 2014' },
    ],
    achievements: ['2023 年材料质检退件率 < 1%', '累计服务 80+ 商科申请者'],
    projects: [
      {
        title: '英港联申材料包',
        result: '一次性通过 6 所学校材料审核',
        description: '搭建共享材料矩阵，避免重复工作。',
      },
    ],
    testimonials: [
      {
        author: '张同学 · LSE Accounting',
        role: '学生',
        comment: '王老师把所有材料做成 checklist，我只需照着准备，效率超高。',
      },
    ],
    metrics: [
      { label: '材料通过率', value: '99%', description: '审核退件率低于 1%' },
      { label: '提交准点率', value: '97%', description: '材料按时提交占比' },
    ],
    availabilityNotes: ['可支持周末面谈', '提供中英双语校对'],
    tools: ['OneDrive', 'Excel', 'Notion'],
  },
  {
    id: 'mentor-3',
    name: '赵倩',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mentor-zhaoqian',
    primaryRole: '质检',
    secondaryRoles: ['顾问'],
    email: 'zhaoqian@example.com',
    phone: '186-8888-9999',
    timezone: 'GMT+8',
    region: '深圳',
    tags: ['文书质检', 'AI评价'],
    languages: ['中文', '英文'],
    availabilityRate: 60,
    utilizationRate: 85,
    studentsCount: 18,
    satisfaction: 4.3,
    risk: '关注',
    lastActivity: '2025-11-06',
    headline: '文书质检官 · 数据驱动评估',
    bio: '曾任 AI 文本质量评估 PM，擅长使用 rubric 打分和 NLP 工具做文书质检。',
    focusAreas: ['文书质检', 'AI 评价', '结构优化'],
    serviceScope: ['终稿质检', '评分报告', '语义优化建议'],
    strengths: ['标准化评分体系', 'AI 辅助审稿', '高并发处理能力'],
    education: [
      { school: '清华大学', degree: '语言技术 · 硕士', period: '2014 - 2017' },
    ],
    achievements: ['构建自研质检打分表，覆盖 30+ 维度', '平均 24 小时内完成反馈'],
    projects: [
      {
        title: 'AI 质检流水线搭建',
        description: '为团队上线 AI 辅助的 draft 评分，效率提升 40%',
        result: '提升交付效率',
      },
    ],
    testimonials: [
      {
        author: '内部顾问团队',
        role: '团队',
        comment: '赵老师的评分报告能够明确指出语义和结构问题，减少大量返工。',
      },
    ],
    metrics: [
      { label: '平均反馈时间', value: '18h', description: '文书质检平均出具时长' },
      { label: '返工率', value: '8%', description: '完成质检后需再修订的比例' },
    ],
    availabilityNotes: ['当前项目较多，建议提前至少 3 天预约'],
    tools: ['Notion', 'ChatGPT Enterprise', 'LanguageTool'],
  },
  {
    id: 'mentor-4',
    name: '李楠',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mentor-linan',
    primaryRole: '面试官',
    secondaryRoles: ['顾问'],
    email: 'linan@example.com',
    phone: '139-2222-3333',
    timezone: 'GMT+9',
    region: '东京',
    tags: ['面试辅导', '日语'],
    languages: ['中文', '英文', '日语'],
    availabilityRate: 64,
    utilizationRate: 58,
    studentsCount: 7,
    satisfaction: 4.9,
    risk: '正常',
    lastActivity: '2025-11-05',
    headline: '海外面试官 · 真题复盘专家',
    bio: '十年跨国企业 HR，现居东京，熟悉英日双语面试流程，擅长案例式问答训练。',
    focusAreas: ['面试辅导', '跨文化沟通', '日语申请'],
    serviceScope: ['结构化面试模拟', '面试反馈报告', '礼仪指导'],
    strengths: ['场景模拟真实', '反馈细致', '熟悉亚洲院校面试风格'],
    education: [
      { school: '早稻田大学', degree: '人力资源管理 · 硕士', period: '2011 - 2013' },
    ],
    achievements: ['模拟面试满意度 4.9', '帮助 45+ 学生拿到日英名校 offer'],
    projects: [
      {
        title: '东京大学面试训练营',
        result: '7 位学生获录取',
        description: '根据真实面试题库设计 5 次迭代训练。',
      },
    ],
    testimonials: [
      {
        author: '陈同学 · 东京大学',
        role: '学生',
        comment: '李老师的反馈很细致，还会纠正我的肢体语言，让我更自信。',
      },
    ],
    metrics: [
      { label: '模拟场次', value: '120+', description: '累计完成模拟面试场次' },
      { label: 'Offer rate', value: '88%', description: '参加训练营学生录取率' },
    ],
    availabilityNotes: ['工作日 18:00 以后 & 周末全天可约', '可提供日语/中文双语指导'],
    tools: ['Zoom', 'Notion', 'Loom'],
  },
];

export const MENTOR_MARKET: MentorRecord[] = [
  {
    id: 'market-1',
    name: 'Grace Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mentor-grace',
    primaryRole: '文书',
    secondaryRoles: ['顾问'],
    email: 'grace.chen@example.com',
    phone: '暂未共享',
    timezone: 'GMT-8',
    region: '旧金山',
    tags: ['计算机', 'Top30', '校友'],
    languages: ['英文', '中文'],
    availabilityRate: 70,
    utilizationRate: 40,
    studentsCount: 0,
    satisfaction: 4.9,
    risk: '正常',
    lastActivity: '2025-11-01',
    referralRate: 92,
    pricePerHour: 480,
    experienceYears: 8,
    headline: '硅谷工程师 · 创业导师',
    bio: '前 Meta Staff Engineer，主攻 AI 产品，辅导过 30+ 工程类申请者，擅长突出技术深度与产品领导力。',
    focusAreas: ['计算机科学', 'AI 产品', '创业故事'],
    strengths: ['硅谷视角', '产品叙事', '技术拆解'],
    education: [
      { school: 'UC Berkeley', degree: 'Computer Science · BS', period: '2009 - 2013' },
    ],
    achievements: ['硅谷校友导师计划核心导师', '帮助 6 位学生拿到 CMU/Stanford Offer'],
    projects: [
      {
        title: 'AI 创业背景包装',
        description: '将学生 AI 社团项目打磨为可落地产品路线',
        result: '获得 CMU MSIN Offer',
      },
    ],
    testimonials: [
      {
        author: 'Jiajun · CMU INI',
        role: '学生',
        comment: 'Grace 会用工程师视角帮你拆亮点，还会分享硅谷公司的真实案例。',
      },
    ],
    metrics: [
      { label: '北美 Offer', value: '30+', description: '累计辅导获得北美 CS 相关 offer 数量' },
    ],
  },
  {
    id: 'market-2',
    name: 'Hannah Lee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mentor-hannah',
    primaryRole: '材料',
    secondaryRoles: ['质检'],
    email: 'hannah.lee@example.com',
    phone: '暂未共享',
    timezone: 'GMT+0',
    region: '伦敦',
    tags: ['金融', '保研', '材料审核'],
    languages: ['英文', '中文'],
    availabilityRate: 88,
    utilizationRate: 30,
    studentsCount: 0,
    satisfaction: 4.7,
    risk: '正常',
    lastActivity: '2025-11-02',
    referralRate: 87,
    pricePerHour: 520,
    experienceYears: 6,
    headline: '投行背景 · 财务材料导师',
    bio: '曾在摩根大通任职，熟悉英港商科项目，擅长挖掘财务案例与职业规划。',
    focusAreas: ['金融', '保研', '材料审核'],
    strengths: ['投行案例', '结构化分析', '多语种支持'],
    education: [
      { school: 'LSE', degree: 'Finance · MSc', period: '2014 - 2015' },
    ],
    achievements: ['帮助 5 位学生获得 LSE/LBS Offer', '搭建保研材料模板库'],
    testimonials: [
      {
        author: 'Yuki · LBS MFA',
        role: '学生',
        comment: 'Hannah 分享的实习案例包装思路很实用，让简历质感提升很多。',
      },
    ],
    metrics: [
      { label: '目标院校命中率', value: '85%', description: '学生进入目标 TOP20 金融项目的比例' },
    ],
  },
  {
    id: 'market-3',
    name: 'Jacob Müller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mentor-jacob',
    primaryRole: '面试官',
    secondaryRoles: ['顾问'],
    email: 'jacob.mueller@example.com',
    phone: '暂未共享',
    timezone: 'GMT+1',
    region: '慕尼黑',
    tags: ['工程', '欧陆申请', '面试官'],
    languages: ['德语', '英文'],
    availabilityRate: 92,
    utilizationRate: 25,
    studentsCount: 0,
    satisfaction: 4.6,
    risk: '正常',
    lastActivity: '2025-11-03',
    referralRate: 89,
    pricePerHour: 450,
    experienceYears: 10,
    headline: '德国工业工程顾问',
    bio: '拥有欧盟注册工程顾问资质，长期服务于德国高校项目申请与实习安排。',
    focusAreas: ['工程管理', '欧陆申请', '面试'],
    strengths: ['欧陆项目经验', '精准定位', '面试辅导'],
    education: [
      { school: 'TUM', degree: 'Engineering Management · MSc', period: '2010 - 2012' },
    ],
    achievements: ['帮助 20+ 学生拿到德语区双录取', '合作企业导师计划评委'],
    testimonials: [
      {
        author: 'Lin · TUM',
        role: '学生',
        comment: 'Jacob 对德语区项目非常熟悉，连生活建议都给得很细。',
      },
    ],
    metrics: [
      { label: '欧陆 Offer', value: '25+', description: '欧盟工程类项目 Offer 数量' },
    ],
  },
];

export const SUMMARY_DATA: SummaryMetric[] = [
  {
    title: '在册导师',
    value: 42,
    trend: '+5 本季度新签',
    positive: true,
    icon: createElement(Users, { className: 'h-5 w-5 text-blue-500' }),
  },
  {
    title: '活跃导师',
    value: '86%',
    trend: '+3.2% 活跃度',
    positive: true,
    icon: createElement(Activity, { className: 'h-5 w-5 text-emerald-500' }),
  },
  {
    title: '平均利用率',
    value: '71%',
    trend: '-4.5% 与上月比较',
    positive: false,
    icon: createElement(Clock4, { className: 'h-5 w-5 text-amber-500' }),
  },
  {
    title: '满意度',
    value: '4.7',
    trend: '+0.2 学生反馈',
    positive: true,
    icon: createElement(Star, { className: 'h-5 w-5 text-purple-500' }),
  },
];

export const SKILL_MATRIX: SkillMatrixEntry[] = [
  { mentor: '刘洋', role: '文书', experience: 6, rating: 4.8, satisfaction: 4.9, language: '中/英' },
  { mentor: '王璐', role: '材料', experience: 5, rating: 4.6, satisfaction: 4.7, language: '中/英' },
  { mentor: '赵倩', role: '质检', experience: 4, rating: 4.5, satisfaction: 4.4, language: '中/英' },
  { mentor: '李楠', role: '面试官', experience: 7, rating: 4.9, satisfaction: 4.9, language: '中/英/日' },
];

export const AVAILABILITY_DATA: AvailabilitySlot[] = [
  { id: 'av-1', mentorId: 'mentor-1', day: '周一', startTime: '09:00', endTime: '12:00', status: '可用' },
  { id: 'av-2', mentorId: 'mentor-1', day: '周三', startTime: '14:00', endTime: '18:00', status: '可用' },
  { id: 'av-3', mentorId: 'mentor-2', day: '周二', startTime: '13:00', endTime: '17:00', status: '忙碌', note: '材料质检任务' },
  { id: 'av-4', mentorId: 'mentor-3', day: '周四', startTime: '10:00', endTime: '16:00', status: '请假', note: '年度培训' },
];

export const MENTOR_TASKS: MentorTask[] = [
  {
    id: 'task-1',
    title: 'PS 第四稿审阅',
    mentor: '刘洋',
    student: '李敏',
    type: '文书',
    status: '进行中',
    deadline: '2025-11-10',
    priority: '高',
  },
  {
    id: 'task-2',
    title: '材料质检 - 成绩单',
    mentor: '王璐',
    student: '王晨',
    type: '材料',
    status: '待开始',
    deadline: '2025-11-12',
    priority: '中',
  },
  {
    id: 'task-3',
    title: '文书质检 - Essay 1',
    mentor: '赵倩',
    student: '李敏',
    type: '质检',
    status: '待审核',
    deadline: '2025-11-09',
    priority: '高',
  },
  {
    id: 'task-4',
    title: 'Columbia 面试模拟',
    mentor: '李楠',
    student: '刘畅',
    type: '面试',
    status: '已完成',
    deadline: '2025-11-05',
    priority: '低',
  },
];

export const INSIGHT_ITEMS: InsightItem[] = [
  {
    title: '质检导师存在过载风险',
    description: '赵倩当前利用率 85%，平均响应时长提升，请评估是否需要分担任务。',
    action: '查看质检任务列表',
  },
  {
    title: '面试导师空闲时段较多',
    description: '李楠未来两周排班较空，可考虑指派更多面试模拟任务。',
    action: '前往排班规划',
  },
  {
    title: '文书满意度持续提升',
    description: '刘洋的学生满意度 4.9，建议整理经验为最佳实践。',
    action: '生成导师经验报告',
  },
];

export const SHARED_RESOURCES: SharedResourceItem[] = [
  {
    id: 'res-guide-1',
    title: '导师 onboarding 手册（2025 版）',
    description: '覆盖服务流程、沟通规范、常见任务模版，适用于内部导师。',
    type: '指南',
    link: '#',
  },
  {
    id: 'res-template-1',
    title: '文书质检 checklist',
    description: '统一质检标准，便于团队共享与审计。',
    type: '模板',
    link: '#',
  },
  {
    id: 'res-case-1',
    title: '导师市场合作案例集',
    description: '合作流程、佣金方案与风险控制建议。',
    type: '案例',
    link: '#',
  },
];
