import { MarketplaceFilterOptions, ProjectItem } from './types';

export const PROJECT_MARKETPLACE_FILTERS: MarketplaceFilterOptions = {
  countries: ['英国', '西班牙', '德国', '中国香港', '新加坡'],
  stages: ['本科', '硕士', '博士', '语言', '职业发展'],
  languages: ['中文', '英文', '西班牙语', '德语'],
  tags: ['奖学金', '保录取', '紧急申请', '官方合作', '双录取', '实习内推', '在线课程'],
};

export const PROJECT_MARKET_ITEMS: ProjectItem[] = [
  {
    id: 'spain-master-fast-track',
    title: '西班牙硕士直录快航计划',
    subtitle: 'Spanish Master Fast Track Program',
    providerName: 'Iberia Pathway Lab',
    providerAvatar: 'https://images.unsplash.com/photo-1522556189639-b150ed9c4330?auto=format&fit=crop&w=200&q=60',
    providerType: '机构',
    country: '西班牙',
    city: '马德里',
    stage: '硕士',
    category: '海外硕士申请',
    highlight: '聚焦商科与设计方向，提供院校官方合作推荐与奖学金加速通道。',
    description:
      '面向希望快速进入西班牙公立及顶尖私立大学硕士项目的学生，覆盖背景评估、定制选校、材料润色与签证落地陪同。项目结合官方合作资源，提供奖学金申请辅导与就业工作坊。',
    coverImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
    languages: ['中文', '英文', '西班牙语'],
    tags: ['奖学金', '官方合作', '紧急申请'],
    focusAreas: ['选校策略', '文书规划', '奖学金申请'],
    supportChannels: ['专属顾问', '每周进度例会', '24h 线上答疑', '签证陪签'],
    successRate: 0.92,
    rating: 4.8,
    reviewCount: 126,
    priceRange: {
      min: 58000,
      max: 78000,
      currency: 'CNY',
    },
    durationWeeks: 28,
    startDates: ['2026 春季', '2026 秋季'],
    packages: [
      {
        name: '标准方案',
        minPrice: 58000,
        currency: 'CNY',
        deliverables: ['背景评估', '定制选校清单（6 所）', '材料润色 3 套', '签证指导'],
      },
      {
        name: '旗舰方案',
        minPrice: 72000,
        currency: 'CNY',
        deliverables: ['导师一对一面试辅导', '奖学金申请规划', '落地安家支持', '就业工坊 3 场'],
        durationWeeks: 32,
      },
    ],
    timeline: [
      { label: 'T-24 周', description: '背景盘点 + 目标拆解 + 语言规划建议' },
      { label: 'T-18 周', description: '完成选校定稿与材料框架设计' },
      { label: 'T-10 周', description: '提交网申 & 奖学金申请' },
      { label: 'T-4 周', description: '签证材料准备与远程面试排期' },
      { label: '入学前', description: '行前说明会 + 就业工作坊' },
    ],
    featured: true,
    insight: '近 30 天咨询量 +36%，奖学金成功率 57%',
    updatedAt: '2025-11-10',
  },
  {
    id: 'germany-dual-degree',
    title: '德国双元制工业实践项目',
    subtitle: 'German Dual Study Industry Immersion',
    providerName: 'Bayern Career Studio',
    providerAvatar: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=200&q=60',
    providerType: '机构',
    country: '德国',
    city: '慕尼黑',
    stage: '本科',
    category: '职业发展 / 本科合作',
    highlight: '结合德国企业实习与高校课程，提供双元制 Offer 全流程辅导与就业签证延长。',
    description:
      '项目合作 30+ 德国制造业企业与应用技术大学，覆盖简历迭代、企业定向面试、德语强化与签证办理。适合拥有理工科背景的准毕业生或跨专业申请者。',
    coverImage: 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=1200&q=80',
    languages: ['中文', '英文', '德语'],
    tags: ['实习内推', '官方合作', '双录取'],
    focusAreas: ['企业匹配', '面试辅导', '德语强化'],
    supportChannels: ['企业导师团', '德语教练', '签证团队', '家长月报'],
    successRate: 0.88,
    rating: 4.7,
    reviewCount: 94,
    priceRange: {
      min: 68000,
      max: 92000,
      currency: 'CNY',
    },
    durationWeeks: 40,
    startDates: ['2026 春季', '2026 秋季'],
    packages: [
      {
        name: '核心方案',
        minPrice: 68000,
        currency: 'CNY',
        deliverables: ['企业偏好评估', '德语集训营 12 周', '双录取网申 3 套', '签证辅导'],
      },
      {
        name: '企业保录计划',
        minPrice: 88000,
        currency: 'CNY',
        deliverables: ['企业导师 1v1', '模拟面试 6 场', '企业现场探访', '延签辅导'],
        seatLimit: 30,
      },
    ],
    timeline: [
      { label: 'T-28 周', description: '德语等级冲刺 + 技能评估' },
      { label: 'T-20 周', description: '企业偏好匹配 & 申请材料准备' },
      { label: 'T-12 周', description: '企业线上/线下面试季' },
      { label: 'T-6 周', description: '高校录取与合同签署' },
      { label: '入职前', description: '入境指导与住宿安排' },
    ],
    featured: true,
    insight: '企业合作扩容至 5 家新能源公司',
    updatedAt: '2025-11-05',
  },
  {
    id: 'uk-law-prep',
    title: '英国法律硕士菁英计划',
    subtitle: 'UK LLM Elite Preparation',
    providerName: 'Commonwealth Legal Studio',
    providerAvatar: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?auto=format&fit=crop&w=200&q=60',
    providerType: '机构',
    country: '英国',
    city: '伦敦',
    stage: '硕士',
    category: '海外硕士申请',
    highlight: '适合冲刺 G5 与顶尖院校法律硕士项目，涵盖律所导师辅导与写作工作坊。',
    description:
      '提供全程学术定位、科研项目推荐、法律写作精修与面试辅导，配套律所导师一对一指导，帮助学生完成从背景提升到 Offer 转化的闭环。',
    coverImage: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&q=80',
    languages: ['中文', '英文'],
    tags: ['保录取', '官方合作', '实习内推'],
    focusAreas: ['科研规划', '职业内推', '面试训练'],
    supportChannels: ['律所导师团', '案例库', 'Offer Tracker', 'WhatsApp 答疑群'],
    successRate: 0.9,
    rating: 4.9,
    reviewCount: 162,
    priceRange: {
      min: 88000,
      max: 128000,
      currency: 'CNY',
    },
    durationWeeks: 36,
    startDates: ['2026 秋季'],
    packages: [
      {
        name: '学术冲刺',
        minPrice: 88000,
        currency: 'CNY',
        deliverables: ['法律写作精修 5 套', '导师模拟面试 4 次', '科研项目推荐', '推荐信指导'],
      },
      {
        name: '律所联培',
        minPrice: 118000,
        currency: 'CNY',
        deliverables: ['Magic Circle 律所导师配对', '法律研讨会 3 场', '暑期实习内推', '就业签证策略'],
      },
    ],
    timeline: [
      { label: 'T-32 周', description: '背景盘点 + 个性化成长路线图' },
      { label: 'T-24 周', description: '科研/实习项目安排 + 写作框架搭建' },
      { label: 'T-16 周', description: '文书定稿 + 推荐信打磨' },
      { label: 'T-8 周', description: '面试训练营 + Offer 跟踪' },
      { label: '入学前', description: '行前准备 & 律所 mentor 结对' },
    ],
    featured: false,
    insight: '近两届 G5 录取率 67%，新增 3 位 Magic Circle 导师',
    updatedAt: '2025-11-09',
  },
  {
    id: 'singapore-ai-internship',
    title: '新加坡 AI Labs 研究实习',
    subtitle: 'Singapore AI Labs Internship Bridge',
    providerName: 'A*Star Talent Hub',
    providerAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=200&q=60',
    providerType: '机构',
    country: '新加坡',
    city: '裕廊',
    stage: '职业发展',
    category: '科研 / 实习',
    highlight: '进入新加坡科研院所 AI 实验室，提供导师配对、课题共创与就业转化指导。',
    description:
      '与新加坡顶尖科研机构合作，提供 AI 算法、计算机视觉、机器人三个方向的研究课题，包含论文共著、成果发表与就业转化支持，适合本科高年级及硕博申请者。',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    languages: ['英文', '中文'],
    tags: ['实习内推', '在线课程'],
    focusAreas: ['科研指导', '论文投稿', '职业转化'],
    supportChannels: ['实验室导师', '周度研讨会', '就业顾问', '线上社群'],
    successRate: 0.86,
    rating: 4.6,
    reviewCount: 58,
    priceRange: {
      min: 52000,
      max: 68000,
      currency: 'CNY',
    },
    durationWeeks: 20,
    startDates: ['2026 春季', '2026 夏季'],
    packages: [
      {
        name: '课题共创',
        minPrice: 52000,
        currency: 'CNY',
        deliverables: ['课题配对', '周度研讨', '成果展示', '就业转化建议'],
      },
      {
        name: '成果发表',
        minPrice: 64000,
        currency: 'CNY',
        deliverables: ['论文写作工作坊', '导师一对一点评', '国际会议投稿辅导'],
      },
    ],
    timeline: [
      { label: 'T-12 周', description: '课题匹配 & 背景审核' },
      { label: 'T-8 周', description: '研究方法训练营 + 数据准备' },
      { label: 'T-2 周', description: '入组准备 & 线上 onboarding' },
      { label: '在组期间', description: '导师每周共创 + 中期评估' },
      { label: '收尾阶段', description: '成果展示 + 就业辅导' },
    ],
    featured: false,
    insight: 'AI 方向新增机器人路径，平均转正率 35%',
    updatedAt: '2025-11-07',
  },
  {
    id: 'hongkong-bilingual-ug',
    title: '香港高校双语国际本科桥梁',
    subtitle: 'Hong Kong Bilingual Undergraduate Bridge',
    providerName: 'Harbour Scholars',
    providerAvatar: 'https://images.unsplash.com/photo-1511367461989-f85a21fda167?auto=format&fit=crop&w=200&q=60',
    providerType: '机构',
    country: '中国香港',
    city: '九龙',
    stage: '本科',
    category: '海外本科申请',
    highlight: '针对内地高二/高三学生，提供双语课程衔接、面试训练与家长陪伴计划。',
    description:
      '结合香港多所高校的预录取名额，提供双语课程桥梁、AI 面试教练、家校联络系统以及家长陪伴计划，帮助家庭快速了解香港升学路径。',
    coverImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    languages: ['中文', '英文'],
    tags: ['双录取', '家长陪伴'],
    focusAreas: ['课程衔接', '面试训练', '家庭沟通'],
    supportChannels: ['班主任制', 'AI 面试模拟', '家长周报', '落地接机'],
    successRate: 0.84,
    rating: 4.5,
    reviewCount: 88,
    priceRange: {
      min: 48000,
      max: 62000,
      currency: 'CNY',
    },
    durationWeeks: 24,
    startDates: ['2026 春季', '2026 秋季'],
    packages: [
      {
        name: '双语衔接班',
        minPrice: 48000,
        currency: 'CNY',
        deliverables: ['双语课程 18 周', '院校面试训练营', '家长陪伴计划'],
      },
      {
        name: '旗舰守护',
        minPrice: 60000,
        currency: 'CNY',
        deliverables: ['院校预录名额', '行前说明会', '住宿安排', '港澳通行证办理指导'],
      },
    ],
    timeline: [
      { label: 'T-20 周', description: '水平评估 + 个性化课程规划' },
      { label: 'T-12 周', description: '双语强化 + 面试工作坊' },
      { label: 'T-4 周', description: '院校面试冲刺 + 家长答疑' },
      { label: 'T-1 周', description: '行前日程确认 + 住宿安排' },
      { label: '入学后', description: '12 周落地适应辅导' },
    ],
    featured: false,
    insight: '家长满意度 4.7/5，新增 2 所合作高校',
    updatedAt: '2025-11-03',
  },
];

